### ISSUE TITLE
Difference with VPT

### ISSUE THREAD

**Issue by jialima-sg** [DongSky/LPT#1]
Thanks for the great work!
I have a question regarding Table 8, where comparison is made between VPT and LPT with different phases. 
Based on my understanding, VPT uses learnable prompts, and is identical to LPT when only Phase 1 is conducted. 
Yet in the table phase 1 and prompt are listed separately. Why?

**Comment by DongSky** [comment]
Compared to VPT, the whole phase 1 includes both shared prompts (like VPT) and the other training techniques (e.g., A-GCL loss, dual-sampling strategy and relative large weight decay) for long-tailed classification, therefore we listed both VPT and phase 1 of LPT separately in the table 8.
